server:
  port: 9090

spring:
  application:
    name: dlx-learn5
  # 配置rabbitmq服务器的信息
  rabbitmq:
    host: 192.168.126.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
# 自定义
my:
  exchangeNormalName: exchange.normal.5 # 正常交换机
  queueNormalName: queue.normal.5 # 正常队列，没有消费者，设置过期时间
  exchangeDlxName: exchange.dlx.5 # 死信交换机
  queueDlxName: queue.dlx.5 #死信队列