server:
  port: 9090

spring:
  application:
    name: headers-exchange
  rabbitmq:
    host: 192.168.126.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode

my:
  exchangeName: exchange.headers
  queueAName: queue.headers.a
  queueBName: queue.headers.b